"""OpenAI-based image generation for outreach variants, via the openai SDK
(already an installed, working dependency in this project -- no new
conflicting package needed, unlike the Gemini path this replaced).

Returns a data: URI (base64-embedded), not a hosted URL, so the frontend
never makes a cross-origin image request for these -- no ORB risk, no
uptime dependency on a third party for the generated bytes themselves.
"""

from __future__ import annotations

import os

try:
    from openai import AsyncOpenAI
except Exception:  # pragma: no cover - optional dependency guard
    AsyncOpenAI = None

_DEFAULT_STYLE_SUFFIX = (
    "Professional B2B SaaS product advertisement photography: a clean modern "
    "analytics dashboard displayed on a laptop or phone screen, studio lighting, "
    "vibrant brand accent colors, high production value social media ad campaign "
    "visual."
)
_NO_TEXT_SUFFIX = (
    "Absolutely no readable text, no words, no letters, no numbers, no logos "
    "anywhere in the image -- treat any on-screen elements as blurred/abstracted "
    "shapes and color blocks only, never legible characters."
)

_client: "AsyncOpenAI | None" = None
_client_initialized = False
_last_error: str | None = None


def get_last_openai_image_error() -> str | None:
    return _last_error


def _set_last_error(message: str | None) -> None:
    global _last_error
    _last_error = message


def _get_client() -> "AsyncOpenAI | None":
    global _client, _client_initialized

    if _client_initialized:
        return _client

    _client_initialized = True
    api_key = os.getenv("OPENAI_API_KEY", "").strip()
    if not api_key or AsyncOpenAI is None:
        _client = None
        return None

    try:
        _client = AsyncOpenAI(api_key=api_key)
    except Exception:
        _client = None

    return _client


def _model_name() -> str:
    return os.getenv("OPENAI_IMAGE_MODEL", "gpt-image-1-mini").strip() or "gpt-image-1-mini"


def _quality() -> str:
    return os.getenv("OPENAI_IMAGE_QUALITY", "low").strip() or "low"


async def generate_variant_image_data_uri(
    *, angle: str, hook: str, product_name: str, style_suffix: str | None = None
) -> str | None:
    client = _get_client()
    if client is None:
        _set_last_error("OPENAI_API_KEY is not set or openai package unavailable")
        return None

    angle_label = (angle or "campaign").replace("_", " ")
    clipped_hook = (hook or "").strip()[:160]
    style = style_suffix or _DEFAULT_STYLE_SUFFIX
    prompt = f"{angle_label} concept for {product_name}: {clipped_hook}. {style} {_NO_TEXT_SUFFIX}"

    try:
        response = await client.images.generate(
            model=_model_name(),
            prompt=prompt,
            n=1,
            size="1024x1024",
            quality=_quality(),  # type: ignore[arg-type]
        )
    except Exception as exc:
        _set_last_error(f"OpenAI image request failed: {str(exc)[:200]}")
        return None

    try:
        b64 = response.data[0].b64_json
    except Exception as exc:
        _set_last_error(f"OpenAI response parsing failed: {str(exc)[:200]}")
        return None

    if not b64:
        _set_last_error("OpenAI response contained no image data")
        return None

    _set_last_error(None)
    return f"data:image/png;base64,{b64}"
