'use client';

import { useCallback, useState } from 'react';

interface CompetitorEntry {
  name: string;
  tagline: string;
  strengths: string[];
  weaknesses: string[];
  highlight?: boolean;
}

type Props = {
  title: string;
  subtitle: string;
  competitors: CompetitorEntry[];
  market_insight: string;
};

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function buildStandaloneHTML(props: Props): string {
  const competitorCards = props.competitors
    .map(
      (comp) => `
      <div style="
        flex: 1 1 220px;
        min-width: 200px;
        background: ${comp.highlight ? 'linear-gradient(135deg, #0f172a 0%, #1e293b 100%)' : '#ffffff'};
        color: ${comp.highlight ? '#f8fafc' : '#0f172a'};
        border-radius: 12px;
        padding: 20px;
        border: ${comp.highlight ? '2px solid #3b82f6' : '1px solid #e2e8f0'};
        position: relative;
        overflow: hidden;
      ">
        ${comp.highlight ? '<div style="position:absolute;top:8px;right:8px;background:#3b82f6;color:#fff;font-size:10px;padding:2px 8px;border-radius:999px;font-weight:600;">OUR PRODUCT</div>' : ''}
        <h3 style="margin:0 0 4px;font-size:16px;font-weight:700;">${comp.name}</h3>
        <p style="margin:0 0 14px;font-size:12px;opacity:0.7;">${comp.tagline}</p>
        <div style="margin-bottom:10px;">
          <p style="font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.5px;margin:0 0 6px;color:${comp.highlight ? '#34d399' : '#059669'};">Strengths</p>
          ${comp.strengths.map((s) => `<p style="margin:0 0 3px;font-size:12px;">✓ ${s}</p>`).join('')}
        </div>
        <div>
          <p style="font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.5px;margin:0 0 6px;color:${comp.highlight ? '#f87171' : '#dc2626'};">Gaps</p>
          ${comp.weaknesses.map((w) => `<p style="margin:0 0 3px;font-size:12px;">✗ ${w}</p>`).join('')}
        </div>
      </div>`
    )
    .join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${props.title}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', sans-serif;
      background: #f8fafc;
      padding: 32px;
    }
  </style>
</head>
<body>
  <div style="max-width:960px;margin:0 auto;">
    <div style="text-align:center;margin-bottom:24px;">
      <h1 style="font-size:24px;font-weight:800;color:#0f172a;margin:0 0 4px;">${props.title}</h1>
      <p style="font-size:13px;color:#64748b;">${props.subtitle}</p>
    </div>
    <div style="display:flex;gap:16px;flex-wrap:wrap;justify-content:center;">
      ${competitorCards}
    </div>
    <div style="margin-top:20px;padding:14px 18px;background:#eff6ff;border-radius:10px;border:1px solid #bfdbfe;">
      <p style="font-size:11px;font-weight:600;text-transform:uppercase;color:#1d4ed8;margin:0 0 4px;">Market Insight</p>
      <p style="font-size:13px;color:#1e40af;margin:0;">${props.market_insight}</p>
    </div>
    <p style="text-align:center;margin-top:16px;font-size:11px;color:#94a3b8;">
      Generated by Vector Agents Signal-to-Action • ${new Date().toLocaleDateString()}
    </p>
  </div>
</body>
</html>`;
}

export function ComparisonCard({ title, subtitle, competitors, market_insight }: Props) {
  const [isDownloadingPng, setIsDownloadingPng] = useState(false);

  const handleDownloadHTML = useCallback(() => {
    const html = buildStandaloneHTML({ title, subtitle, competitors, market_insight });
    const blob = new Blob([html], { type: 'text/html' });
    downloadBlob(blob, 'comparison-card.html');
  }, [title, subtitle, competitors, market_insight]);

  const handleDownloadPNG = useCallback(async () => {
    // Server-rendered via next/og (Satori) from the same structured data --
    // deterministic and data-accurate, not a client-side canvas screenshot.
    setIsDownloadingPng(true);
    try {
      const response = await fetch('/api/og/comparison', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ title, subtitle, competitors, market_insight }),
      });
      if (!response.ok) {
        throw new Error(`OG image route returned ${response.status}`);
      }
      const blob = await response.blob();
      downloadBlob(blob, 'comparison-card.png');
    } catch {
      handleDownloadHTML();
    } finally {
      setIsDownloadingPng(false);
    }
  }, [title, subtitle, competitors, market_insight, handleDownloadHTML]);

  return (
    <section className="rounded-2xl border border-slate-200/70 bg-white/80 p-5 shadow-lg shadow-slate-200/40 backdrop-blur dark:border-slate-800 dark:bg-slate-950/65 dark:shadow-none">
      <div className="mb-4 flex items-start justify-between">
        <div>
          <h2 className="text-lg font-bold text-slate-900 dark:text-slate-100">{title}</h2>
          <p className="text-xs text-slate-500 dark:text-slate-400">{subtitle}</p>
        </div>
        <div className="flex gap-2">
          <button
            type="button"
            onClick={handleDownloadHTML}
            className="rounded-lg border border-slate-300 bg-white px-3 py-1.5 text-xs font-semibold text-slate-700 transition hover:bg-slate-100 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200 dark:hover:bg-slate-800"
          >
            ↓ HTML
          </button>
          <button
            type="button"
            disabled={isDownloadingPng}
            onClick={() => void handleDownloadPNG()}
            className="rounded-lg bg-linear-to-r from-indigo-600 to-blue-600 px-3 py-1.5 text-xs font-semibold text-white shadow transition hover:from-indigo-500 hover:to-blue-500 disabled:opacity-60"
          >
            {isDownloadingPng ? 'Rendering…' : '↓ PNG'}
          </button>
        </div>
      </div>

      <div className="rounded-xl border border-slate-200 bg-slate-50/90 p-4 dark:border-slate-800 dark:bg-slate-900/70">
        <div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">
          {competitors.map((comp) => (
            <article
              key={comp.name}
              className={`relative overflow-hidden rounded-xl p-4 ${
                comp.highlight
                  ? 'border-2 border-blue-500 bg-linear-to-br from-slate-900 to-slate-800 text-slate-50 shadow-md'
                  : 'border border-slate-200 bg-white text-slate-900 shadow-sm dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100'
              }`}
            >
              {comp.highlight && (
                <span className="absolute right-2 top-2 rounded-full bg-blue-500 px-2 py-0.5 text-[10px] font-semibold text-white">
                  OUR PRODUCT
                </span>
              )}
              <h3 className="text-sm font-bold">{comp.name}</h3>
              <p className={`mb-3 text-xs ${comp.highlight ? 'text-slate-300' : 'text-slate-500 dark:text-slate-400'}`}>
                {comp.tagline}
              </p>

              <div className="mb-2">
                <p
                  className={`mb-1 text-[10px] font-semibold uppercase tracking-wide ${
                    comp.highlight ? 'text-emerald-400' : 'text-emerald-600'
                  }`}
                >
                  Strengths
                </p>
                {comp.strengths.map((s) => (
                  <p key={s} className="text-xs leading-relaxed">
                    ✓ {s}
                  </p>
                ))}
              </div>

              <div>
                <p
                  className={`mb-1 text-[10px] font-semibold uppercase tracking-wide ${
                    comp.highlight ? 'text-red-400' : 'text-red-600'
                  }`}
                >
                  Gaps
                </p>
                {comp.weaknesses.map((w) => (
                  <p key={w} className="text-xs leading-relaxed">
                    ✗ {w}
                  </p>
                ))}
              </div>
            </article>
          ))}
        </div>

        <div className="mt-3 rounded-lg border border-blue-200 bg-blue-50 px-4 py-3 dark:border-blue-500/30 dark:bg-blue-950/40">
          <p className="mb-1 text-[10px] font-semibold uppercase tracking-wide text-blue-700">
            Market Insight
          </p>
          <p className="text-xs text-blue-900 dark:text-blue-100">{market_insight}</p>
        </div>

        <p className="mt-2 text-center text-[10px] text-slate-400 dark:text-slate-500">
          Generated by Vector Agents Signal-to-Action • {new Date().toLocaleDateString()}
        </p>
      </div>
    </section>
  );
}
