'use client';

import { useCallback, useRef } from 'react';

interface CompetitorEntry {
  name: string;
  tagline: string;
  strengths: string[];
  weaknesses: string[];
  highlight?: boolean;
}

type Props = {
  title: string;
  subtitle: string;
  competitors: CompetitorEntry[];
  market_insight: string;
};

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function buildStandaloneHTML(props: Props): string {
  const competitorCards = props.competitors
    .map(
      (comp) => `
      <div style="
        flex: 1 1 220px;
        min-width: 200px;
        background: ${comp.highlight ? 'linear-gradient(135deg, #0f172a 0%, #1e293b 100%)' : '#ffffff'};
        color: ${comp.highlight ? '#f8fafc' : '#0f172a'};
        border-radius: 12px;
        padding: 20px;
        border: ${comp.highlight ? '2px solid #3b82f6' : '1px solid #e2e8f0'};
        position: relative;
        overflow: hidden;
      ">
        ${comp.highlight ? '<div style="position:absolute;top:8px;right:8px;background:#3b82f6;color:#fff;font-size:10px;padding:2px 8px;border-radius:999px;font-weight:600;">OUR PRODUCT</div>' : ''}
        <h3 style="margin:0 0 4px;font-size:16px;font-weight:700;">${comp.name}</h3>
        <p style="margin:0 0 14px;font-size:12px;opacity:0.7;">${comp.tagline}</p>
        <div style="margin-bottom:10px;">
          <p style="font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.5px;margin:0 0 6px;color:${comp.highlight ? '#34d399' : '#059669'};">Strengths</p>
          ${comp.strengths.map((s) => `<p style="margin:0 0 3px;font-size:12px;">✓ ${s}</p>`).join('')}
        </div>
        <div>
          <p style="font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.5px;margin:0 0 6px;color:${comp.highlight ? '#f87171' : '#dc2626'};">Gaps</p>
          ${comp.weaknesses.map((w) => `<p style="margin:0 0 3px;font-size:12px;">✗ ${w}</p>`).join('')}
        </div>
      </div>`
    )
    .join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${props.title}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', sans-serif;
      background: #f8fafc;
      padding: 32px;
    }
  </style>
</head>
<body>
  <div style="max-width:960px;margin:0 auto;">
    <div style="text-align:center;margin-bottom:24px;">
      <h1 style="font-size:24px;font-weight:800;color:#0f172a;margin:0 0 4px;">${props.title}</h1>
      <p style="font-size:13px;color:#64748b;">${props.subtitle}</p>
    </div>
    <div style="display:flex;gap:16px;flex-wrap:wrap;justify-content:center;">
      ${competitorCards}
    </div>
    <div style="margin-top:20px;padding:14px 18px;background:#eff6ff;border-radius:10px;border:1px solid #bfdbfe;">
      <p style="font-size:11px;font-weight:600;text-transform:uppercase;color:#1d4ed8;margin:0 0 4px;">Market Insight</p>
      <p style="font-size:13px;color:#1e40af;margin:0;">${props.market_insight}</p>
    </div>
    <p style="text-align:center;margin-top:16px;font-size:11px;color:#94a3b8;">
      Generated by Vector Agents Signal-to-Action • ${new Date().toLocaleDateString()}
    </p>
  </div>
</body>
</html>`;
}

function renderToPNG(element: HTMLElement): Promise<Blob> {
  return new Promise((resolve, reject) => {
    const canvas = document.createElement('canvas');
    const scale = 2;
    const rect = element.getBoundingClientRect();
    canvas.width = rect.width * scale;
    canvas.height = rect.height * scale;
    const ctx = canvas.getContext('2d');
    if (!ctx) {
      reject(new Error('Canvas not supported'));
      return;
    }

    const svgData = `
      <foreignObject width="${rect.width}" height="${rect.height}">
        <div xmlns="http://www.w3.org/1999/xhtml">
          ${element.outerHTML}
        </div>
      </foreignObject>
    `;
    const svgBlob = new Blob(
      [
        `<svg xmlns="http://www.w3.org/2000/svg" width="${rect.width * scale}" height="${rect.height * scale}" viewBox="0 0 ${rect.width} ${rect.height}">${svgData}</svg>`,
      ],
      { type: 'image/svg+xml;charset=utf-8' }
    );
    const url = URL.createObjectURL(svgBlob);
    const img = new Image();
    img.onload = () => {
      ctx.drawImage(img, 0, 0);
      URL.revokeObjectURL(url);
      canvas.toBlob(
        (blob) => {
          if (blob) resolve(blob);
          else reject(new Error('PNG conversion failed'));
        },
        'image/png',
        1.0
      );
    };
    img.onerror = () => {
      URL.revokeObjectURL(url);
      // Fallback: download as HTML instead
      const html = element.outerHTML;
      resolve(new Blob([html], { type: 'text/html' }));
    };
    img.src = url;
  });
}

export function ComparisonCard({ title, subtitle, competitors, market_insight }: Props) {
  const cardRef = useRef<HTMLDivElement>(null);

  const handleDownloadHTML = useCallback(() => {
    const html = buildStandaloneHTML({ title, subtitle, competitors, market_insight });
    const blob = new Blob([html], { type: 'text/html' });
    downloadBlob(blob, 'comparison-card.html');
  }, [title, subtitle, competitors, market_insight]);

  const handleDownloadPNG = useCallback(async () => {
    if (!cardRef.current) return;
    try {
      const blob = await renderToPNG(cardRef.current);
      downloadBlob(blob, blob.type.includes('html') ? 'comparison-card.html' : 'comparison-card.png');
    } catch {
      // Fallback to HTML download on any canvas/security error
      handleDownloadHTML();
    }
  }, [handleDownloadHTML]);

  return (
    <section className="rounded-xl border border-zinc-200 p-5 shadow-sm">
      <div className="mb-4 flex items-start justify-between">
        <div>
          <h2 className="text-lg font-bold">{title}</h2>
          <p className="text-xs text-zinc-500">{subtitle}</p>
        </div>
        <div className="flex gap-2">
          <button
            type="button"
            onClick={handleDownloadHTML}
            className="rounded-md border border-zinc-300 px-3 py-1.5 text-xs font-medium hover:bg-zinc-50"
          >
            ↓ HTML
          </button>
          <button
            type="button"
            onClick={() => void handleDownloadPNG()}
            className="rounded-md bg-blue-600 px-3 py-1.5 text-xs font-medium text-white hover:bg-blue-700"
          >
            ↓ PNG
          </button>
        </div>
      </div>

      <div ref={cardRef} className="rounded-lg bg-slate-50 p-4">
        <div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">
          {competitors.map((comp) => (
            <article
              key={comp.name}
              className={`relative overflow-hidden rounded-xl p-4 ${
                comp.highlight
                  ? 'border-2 border-blue-500 bg-gradient-to-br from-slate-900 to-slate-800 text-slate-50'
                  : 'border border-zinc-200 bg-white text-slate-900'
              }`}
            >
              {comp.highlight && (
                <span className="absolute right-2 top-2 rounded-full bg-blue-500 px-2 py-0.5 text-[10px] font-semibold text-white">
                  OUR PRODUCT
                </span>
              )}
              <h3 className="text-sm font-bold">{comp.name}</h3>
              <p className={`mb-3 text-xs ${comp.highlight ? 'text-slate-400' : 'text-zinc-500'}`}>
                {comp.tagline}
              </p>

              <div className="mb-2">
                <p
                  className={`mb-1 text-[10px] font-semibold uppercase tracking-wide ${
                    comp.highlight ? 'text-emerald-400' : 'text-emerald-600'
                  }`}
                >
                  Strengths
                </p>
                {comp.strengths.map((s) => (
                  <p key={s} className="text-xs leading-relaxed">
                    ✓ {s}
                  </p>
                ))}
              </div>

              <div>
                <p
                  className={`mb-1 text-[10px] font-semibold uppercase tracking-wide ${
                    comp.highlight ? 'text-red-400' : 'text-red-600'
                  }`}
                >
                  Gaps
                </p>
                {comp.weaknesses.map((w) => (
                  <p key={w} className="text-xs leading-relaxed">
                    ✗ {w}
                  </p>
                ))}
              </div>
            </article>
          ))}
        </div>

        <div className="mt-3 rounded-lg border border-blue-200 bg-blue-50 px-4 py-3">
          <p className="mb-1 text-[10px] font-semibold uppercase tracking-wide text-blue-700">
            Market Insight
          </p>
          <p className="text-xs text-blue-900">{market_insight}</p>
        </div>

        <p className="mt-2 text-center text-[10px] text-zinc-400">
          Generated by Vector Agents Signal-to-Action • {new Date().toLocaleDateString()}
        </p>
      </div>
    </section>
  );
}
